# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: schoolwork
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: notesapi
# "service" is the name of this project. This will also be added to your AWS resource names.
service: notesapi

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1 # Specify the AWS region
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/NotesTable"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/UsersTable"

functions:
  signUpUser:
    handler: postUsers/postUsers.signup
    events:
      - httpApi:
          path: /api/user/signup
          method: post

  createNote:
    handler: postNotes/postNotes.createNote
    events:
      - httpApi:
          path: /api/notes
          method: post

resources:
  Resources:
    NotesTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: NotesTable
        AttributeDefinitions:
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: noteId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    UsersTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
